### ISSUE TITLE
Roadmap for implementing the data layer

### ISSUE THREAD

**Issue by SteveRyan-ASU** [asuengineering/pitchfork-blocks#11]
**Determine which blocks will need to be altered so that they have the correct attributes for the ASU GA4 data layer.**

Will likely create new issues for each element to be altered. 

- [ ] acf/accordions (expand/contract)
- [ ] acf/alert (dismissal)
- [ ] acf/card (button click)
- [ ] acf/sidebar (mobile dropdown)

**Comment by SteveRyan-ASU** [comment]
Closing the issue. As of the v2.1 release all of the above data layer supporting mechanisms listed above are implemented.
